In [1]:
import pandas as pd
from sqlalchemy import create_engine

df = pd.read_csv("../data/cleaned/final_jobs_dataset.csv")

df.head()

,job_id,job_title,salary_usd,salary_currency,experience_level,employment_type,company_location,company_size,employee_residence,remote_ratio,...,benefits_score,company_name,experience_level_clean,employment_type_clean,company_size_clean,work_type,skills_list,skill_count,role_category,experience_category
0,AI00001,AI Research Scientist,90376,USD,SE,CT,China,M,China,50,...,5.9,Smart Analytics,Senior Level,Contract,Medium,Hybrid,"['tableau', 'pytorch', 'kubernetes', 'linux', ...",5,Data Scientist,Senior Level
1,AI00002,AI Software Engineer,61895,USD,EN,CT,Canada,M,Ireland,100,...,5.2,TechCorp Inc,Entry Level,Contract,Medium,Remote,"['deep learning', 'aws', 'mathematics', 'pytho...",5,Data Engineer,Entry Level
2,AI00003,AI Specialist,152626,USD,MI,FL,Switzerland,L,South Korea,0,...,9.4,Autonomous Tech,Mid Level,Freelance,Large,On-site,"['kubernetes', 'deep learning', 'java', 'hadoo...",5,AI Engineer,Entry Level
3,AI00004,NLP Engineer,80215,USD,SE,FL,India,M,India,50,...,8.6,Future Systems,Senior Level,Freelance,Medium,Hybrid,"['scala', 'sql', 'linux', 'python']",4,Data Engineer,Senior Level
4,AI00005,AI Consultant,54624,EUR,EN,PT,France,S,Singapore,100,...,6.6,Advanced Robotics,Entry Level,Part Time,Small,Remote,"['mlops', 'java', 'tableau', 'python']",4,AI Engineer,Entry Level

In [3]:
engine = create_engine(
    "postgresql+psycopg2://postgres:60801787@localhost:5432/job_market_db"
)

In [4]:
df.to_sql(
    "jobs",
    engine,
    if_exists="replace",
    index=False
)

print("Data exported to PostgreSQL successfully!")

Data exported to PostgreSQL successfully!

In [5]:
query = """
SELECT COUNT(*) AS total_jobs
FROM jobs;
"""

pd.read_sql(query, engine)

   total_jobs
0       15000