In [1]:
import pandas as pd
from sqlalchemy import create_engine

df = pd.read_csv("../data/cleaned/final_jobs_dataset.csv")

df.head()

,job_id,job_title,salary_usd,salary_currency,experience_level,employment_type,company_location,company_size,employee_residence,remote_ratio,...,benefits_score,company_name,experience_level_clean,employment_type_clean,company_size_clean,work_type,skills_list,skill_count,role_category,experience_category
0,AI00001,AI Research Scientist,90376,USD,SE,CT,China,M,China,50,...,5.9,Smart Analytics,Senior Level,Contract,Medium,Hybrid,"['tableau', 'pytorch', 'kubernetes', 'linux', ...",5,Data Scientist,Senior Level
1,AI00002,AI Software Engineer,61895,USD,EN,CT,Canada,M,Ireland,100,...,5.2,TechCorp Inc,Entry Level,Contract,Medium,Remote,"['deep learning', 'aws', 'mathematics', 'pytho...",5,Data Engineer,Entry Level
2,AI00003,AI Specialist,152626,USD,MI,FL,Switzerland,L,South Korea,0,...,9.4,Autonomous Tech,Mid Level,Freelance,Large,On-site,"['kubernetes', 'deep learning', 'java', 'hadoo...",5,AI Engineer,Entry Level
3,AI00004,NLP Engineer,80215,USD,SE,FL,India,M,India,50,...,8.6,Future Systems,Senior Level,Freelance,Medium,Hybrid,"['scala', 'sql', 'linux', 'python']",4,Data Engineer,Senior Level
4,AI00005,AI Consultant,54624,EUR,EN,PT,France,S,Singapore,100,...,6.6,Advanced Robotics,Entry Level,Part Time,Small,Remote,"['mlops', 'java', 'tableau', 'python']",4,AI Engineer,Entry Level

In [2]:
df[["job_id", "job_title", "required_skills"]].head()

,job_id,job_title,required_skills
0,AI00001,AI Research Scientist,"tableau, pytorch, kubernetes, linux, nlp"
1,AI00002,AI Software Engineer,"deep learning, aws, mathematics, python, docker"
2,AI00003,AI Specialist,"kubernetes, deep learning, java, hadoop, nlp"
3,AI00004,NLP Engineer,"scala, sql, linux, python"
4,AI00005,AI Consultant,"mlops, java, tableau, python"

In [3]:
skills_df = df[
    [
        "job_id",
        "job_title",
        "role_category",
        "experience_category",
        "work_type",
        "salary_usd",
        "required_skills"
    ]
].copy()

skills_df["skill"] = skills_df["required_skills"].str.split(",")

skills_df = skills_df.explode("skill")

skills_df["skill"] = skills_df["skill"].str.strip().str.lower()

skills_df = skills_df[skills_df["skill"].notna()]
skills_df = skills_df[skills_df["skill"] != ""]

skills_df.head()

,job_id,job_title,role_category,experience_category,work_type,salary_usd,required_skills,skill
0,AI00001,AI Research Scientist,Data Scientist,Senior Level,Hybrid,90376,"tableau, pytorch, kubernetes, linux, nlp",tableau
0,AI00001,AI Research Scientist,Data Scientist,Senior Level,Hybrid,90376,"tableau, pytorch, kubernetes, linux, nlp",pytorch
0,AI00001,AI Research Scientist,Data Scientist,Senior Level,Hybrid,90376,"tableau, pytorch, kubernetes, linux, nlp",kubernetes
0,AI00001,AI Research Scientist,Data Scientist,Senior Level,Hybrid,90376,"tableau, pytorch, kubernetes, linux, nlp",linux
0,AI00001,AI Research Scientist,Data Scientist,Senior Level,Hybrid,90376,"tableau, pytorch, kubernetes, linux, nlp",nlp

In [4]:
print("Original jobs rows:", df.shape[0])
print("Skills table rows:", skills_df.shape[0])

skills_df.head(20)

Original jobs rows: 15000
Skills table rows: 59893

,job_id,job_title,role_category,experience_category,work_type,salary_usd,required_skills,skill
0,AI00001,AI Research Scientist,Data Scientist,Senior Level,Hybrid,90376,"tableau, pytorch, kubernetes, linux, nlp",tableau
0,AI00001,AI Research Scientist,Data Scientist,Senior Level,Hybrid,90376,"tableau, pytorch, kubernetes, linux, nlp",pytorch
0,AI00001,AI Research Scientist,Data Scientist,Senior Level,Hybrid,90376,"tableau, pytorch, kubernetes, linux, nlp",kubernetes
0,AI00001,AI Research Scientist,Data Scientist,Senior Level,Hybrid,90376,"tableau, pytorch, kubernetes, linux, nlp",linux
0,AI00001,AI Research Scientist,Data Scientist,Senior Level,Hybrid,90376,"tableau, pytorch, kubernetes, linux, nlp",nlp
1,AI00002,AI Software Engineer,Data Engineer,Entry Level,Remote,61895,"deep learning, aws, mathematics, python, docker",deep learning
1,AI00002,AI Software Engineer,Data Engineer,Entry Level,Remote,61895,"deep learning, aws, mathematics, python, docker",aws
1,AI00002,AI Software Engineer,Data Engineer,Entry Level,Remote,61895,"deep learning, aws, mathematics, python, docker",mathematics
1,AI00002,AI Software Engineer,Data Engineer,Entry Level,Remote,61895,"deep learning, aws, mathematics, python, docker",python
1,AI00002,AI Software Engineer,Data Engineer,Entry Level,Remote,61895,"deep learning, aws, mathematics, python, docker",docker
2,AI00003,AI Specialist,AI Engineer,Entry Level,On-site,152626,"kubernetes, deep learning, java, hadoop, nlp",kubernetes
2,AI00003,AI Specialist,AI Engineer,Entry Level,On-site,152626,"kubernetes, deep learning, java, hadoop, nlp",deep learning
2,AI00003,AI Specialist,AI Engineer,Entry Level,On-site,152626,"kubernetes, deep learning, java, hadoop, nlp",java
2,AI00003,AI Specialist,AI Engineer,Entry Level,On-site,152626,"kubernetes, deep learning, java, hadoop, nlp",hadoop
2,AI00003,AI Specialist,AI Engineer,Entry Level,On-site,152626,"kubernetes, deep learning, java, hadoop, nlp",nlp
3,AI00004,NLP Engineer,Data Engineer,Senior Level,Hybrid,80215,"scala, sql, linux, python",scala
3,AI00004,NLP Engineer,Data Engineer,Senior Level,Hybrid,80215,"scala, sql, linux, python",sql
3,AI00004,NLP Engineer,Data Engineer,Senior Level,Hybrid,80215,"scala, sql, linux, python",linux
3,AI00004,NLP Engineer,Data Engineer,Senior Level,Hybrid,80215,"scala, sql, linux, python",python
4,AI00005,AI Consultant,AI Engineer,Entry Level,Remote,54624,"mlops, java, tableau, python",mlops

In [5]:
skills_df.to_csv("../data/cleaned/job_skills.csv", index=False)

print("job_skills.csv saved successfully!")

job_skills.csv saved successfully!

In [6]:
engine = create_engine(
    "postgresql+psycopg2://postgres:60801787@localhost:5432/job_market_db"
)

skills_df.to_sql(
    "job_skills",
    engine,
    if_exists="replace",
    index=False
)

print("job_skills table exported to PostgreSQL successfully!")

job_skills table exported to PostgreSQL successfully!

In [7]:
query = """
SELECT skill,
       COUNT(*) AS total_mentions
FROM job_skills
GROUP BY skill
ORDER BY total_mentions DESC
LIMIT 10;
"""

pd.read_sql(query, engine)

        skill  total_mentions
0      python            4450
1         sql            3407
2  tensorflow            3022
3  kubernetes            3009
4       scala            2794
5     pytorch            2777
6       linux            2705
7         git            2631
8        java            2578
9         gcp            2442