In [1]:
import pandas as pd
from sqlalchemy import create_engine

df_live = pd.read_csv("../data/scraped/live_jobs.csv")

df_live.head()

,job_id,job_title,company,location,country,employment_type,job_description,date_posted,job_url,publisher,is_remote,salary_min,salary_max,salary_period,search_query,api_source
0,9DfZj0CdZvFSLCUiAAAAAA==,Junior Data System Analyst,SRG,Marlow,GB,NaN,• Role Title: Junior Data System Analyst\n• Co...,2026-05-22T00:00:00.000Z,https://uk.linkedin.com/jobs/view/junior-data-...,LinkedIn,False,NaN,NaN,NaN,data analyst in United Kingdom,JSearch
1,zTVCZ8KoO1CRpTMgAAAAAA==,Senior Data Analyst,Scrumconnect Consulting,Staines-upon-Thames,GB,Full–time,Job Description\n\nAbout Scrumconnect Consulti...,2026-05-23T00:00:00.000Z,https://uk.linkedin.com/jobs/view/senior-data-...,LinkedIn,False,NaN,NaN,NaN,data analyst in United Kingdom,JSearch
2,X2MCwACWKPsgsvVOAAAAAA==,Data analyst,Randstad Delivery,Cambridgeshire,GB,Full–time,Job Description: Business Change Analyst (Data...,2026-05-22T00:00:00.000Z,https://bebee.com/gb/jobs/data-analyst-randsta...,BeBee,False,NaN,NaN,NaN,data analyst in United Kingdom,JSearch
3,hH-eVZIhJR_gi_SEAAAAAA==,Senior Data Analyst - Department for Education...,Manchester Digital,Manchester,GB,Full–time,"Locations: Coventry, Manchester, Sheffield, Lo...",2026-05-21T00:00:00.000Z,https://uk.linkedin.com/jobs/view/senior-data-...,LinkedIn,False,NaN,NaN,NaN,data analyst in United Kingdom,JSearch
4,n9IO89ETIut2BOJ3AAAAAA==,Data Analyst,Gill Cooke Personnel Ltd T/A The Recruitment G...,Carterton,GB,Full–time,Temporary Data Analyst\n\nLocation: Oxfordshir...,2026-05-20T00:00:00.000Z,https://jobs.womenforhire.com/job/united-kingd...,Women For Hire - Job Board,False,NaN,NaN,NaN,data analyst in United Kingdom,JSearch

In [2]:
print(df_live.shape)
print(df_live.columns)
df_live.info()

(70, 16)
Index(['job_id', 'job_title', 'company', 'location', 'country',
       'employment_type', 'job_description', 'date_posted', 'job_url',
       'publisher', 'is_remote', 'salary_min', 'salary_max', 'salary_period',
       'search_query', 'api_source'],
      dtype='object')
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 70 entries, 0 to 69
Data columns (total 16 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   job_id           70 non-null     object
 1   job_title        70 non-null     object
 2   company          70 non-null     object
 3   location         70 non-null     object
 4   country          66 non-null     object
 5   employment_type  67 non-null     object
 6   job_description  70 non-null     object
 7   date_posted      70 non-null     object
 8   job_url          70 non-null     object
 9   publisher        70 non-null     object
 10  is_remote        70 non-null     bool
 11  salary_min       0 non-null      float64
 12  salary_max       0 non-null      float64
 13  salary_period    0 non-null      float64
 14  search_query     70 non-null     object
 15  api_source       70 non-null     object
dtypes: bool(1), float64(3), object(12)
memory usage: 8.4+ KB

In [5]:
from sqlalchemy import create_engine

engine = create_engine(
    "postgresql+psycopg2://postgres:60801787@localhost:5432/job_market_db"
)

In [6]:
df_live.to_sql(
    "live_jobs",
    engine,
    if_exists="replace",
    index=False
)

print("live_jobs table exported successfully!")

live_jobs table exported successfully!

In [7]:
query = """
SELECT COUNT(*) AS total_live_jobs
FROM live_jobs;
"""

pd.read_sql(query, engine)

   total_live_jobs
0               70